pipeline {
    agent any

    environment {
        FRONTEND_IMAGE = 'ahilan0143/ecommerce-frontend'
        BACKEND_IMAGE  = 'ahilan0143/ecommerce-backend'
        IMAGE_TAG = "${BUILD_NUMBER}"
        KUBE_NAMESPACE = 'ecommerce'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/YOUR_GITHUB_USERNAME/ecommerce-app.git'
            }
        }

        stage('Build Backend Image') {
            steps {
                dir('backend') {
                    sh 'docker build -t $BACKEND_IMAGE:$IMAGE_TAG .'
                    sh 'docker tag $BACKEND_IMAGE:$IMAGE_TAG $BACKEND_IMAGE:latest'
                }
            }
        }

        stage('Build Frontend Image') {
            steps {
                dir('frontend') {
                    sh 'docker build -t $FRONTEND_IMAGE:$IMAGE_TAG .'
                    sh 'docker tag $FRONTEND_IMAGE:$IMAGE_TAG $FRONTEND_IMAGE:latest'
                }
            }
        }

        stage('Docker Login') {
            steps {
                withCredentials([usernamePassword(credentialsId: 'dockerhub-cred', usernameVariable: 'DOCKER_USER', passwordVariable: 'DOCKER_PASS')]) {
                    sh 'echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin'
                }
            }
        }

        stage('Push Images') {
            steps {
                sh 'docker push $BACKEND_IMAGE:$IMAGE_TAG'
                sh 'docker push $BACKEND_IMAGE:latest'
                sh 'docker push $FRONTEND_IMAGE:$IMAGE_TAG'
                sh 'docker push $FRONTEND_IMAGE:latest'
            }
        }

        stage('Deploy to Kubernetes') {
            steps {
                sh 'kubectl apply -f k8s/'
                sh "kubectl set image deployment/backend-deployment backend=$BACKEND_IMAGE:$IMAGE_TAG -n $KUBE_NAMESPACE"
                sh "kubectl set image deployment/frontend-deployment frontend=$FRONTEND_IMAGE:$IMAGE_TAG -n $KUBE_NAMESPACE"
            }
        }
    }
}